name: color_tile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  quiver: ^3.2.1
  mockito: ^5.3.2
  freezed_annotation: ^2.2.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.5
  device_info_plus: ^8.1.0
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.12.0

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/hint.png

  fonts:
    - family: DotGothic16
      fonts:
        - asset: lib/assets/fonts/DotGothic16-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/icons/icon.png
  web:
    generate: true
    image_path: lib/assets/icons/icon.png
    background_color: "0xFFFFFFFF"
    theme_color: "0xFFFFFFFF"
