// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUqpkpOmndJoymo3ZDT0kJ69vX4so-qJM',
    appId: '1:489283794321:web:0993d72d11504ba3089630',
    messagingSenderId: '489283794321',
    projectId: 'artile-af62f',
    authDomain: 'artile-af62f.firebaseapp.com',
    storageBucket: 'artile-af62f.appspot.com',
    measurementId: 'G-LKLZM0SLWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd2uFcJc69uD-kXxUL7VVYKUs_MAlr3tA',
    appId: '1:489283794321:android:b197f9cee7861e24089630',
    messagingSenderId: '489283794321',
    projectId: 'artile-af62f',
    storageBucket: 'artile-af62f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSregFh7Rm6MjfM-4RlGPQFN_oKeYZGHE',
    appId: '1:489283794321:ios:26a13a5c567b0eb2089630',
    messagingSenderId: '489283794321',
    projectId: 'artile-af62f',
    storageBucket: 'artile-af62f.appspot.com',
    iosClientId: '489283794321-cf3mi52vplbus0fcuu1kar8occi7a3n0.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorTile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSregFh7Rm6MjfM-4RlGPQFN_oKeYZGHE',
    appId: '1:489283794321:ios:26a13a5c567b0eb2089630',
    messagingSenderId: '489283794321',
    projectId: 'artile-af62f',
    storageBucket: 'artile-af62f.appspot.com',
    iosClientId: '489283794321-cf3mi52vplbus0fcuu1kar8occi7a3n0.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorTile',
  );
}
