// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO9yMfrDOqUCJ1YU0_0hyvQlTQIIj-asI',
    appId: '1:1068043452365:web:028ee90ee2eadd49e54e84',
    messagingSenderId: '1068043452365',
    projectId: 'artile-dev',
    authDomain: 'artile-dev.firebaseapp.com',
    storageBucket: 'artile-dev.appspot.com',
    measurementId: 'G-XR12P7LN9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8wkMwM4DPCaUROTbjTxrLY_B1prStpk',
    appId: '1:1068043452365:android:3050fea4cd5d51fee54e84',
    messagingSenderId: '1068043452365',
    projectId: 'artile-dev',
    storageBucket: 'artile-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI_QCa2OE1qD71j-TYfh8cGe6rVTo5TMY',
    appId: '1:1068043452365:ios:c0d457ba920fde9ce54e84',
    messagingSenderId: '1068043452365',
    projectId: 'artile-dev',
    storageBucket: 'artile-dev.appspot.com',
    iosClientId: '1068043452365-8u5ico23decmgabifh8o096bdhhj62d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorTile',
  );
}
